job_details:
  name: diff_no_softmax_constant_lr_sweep_condensed
  output_dir: logs/seeds_and_datasets

parameters:
  LIST_DATASETS:
    # - input_bin: ["data/fineweb10B/fineweb_train_*.bin"]
    #   input_val_bin: ["data/fineweb10B/fineweb_train_*.bin"]
    # - input_bin: ["data/tokenized_owt2/train.bin"]
    #   input_val_bin: ["data/tokenized_owt2/val.bin"]
    - input_bin: ["/p/data1/mmlaion/text-data/tokenized/c4/merged"]
      input_val_bin: ["/p/data1/mmlaion/text-data/tokenized/c4/merged"]

  # Model parameters
  vocab_size: [50304]
  n_layer: [12]
  n_head: [6] # change to 12?
  n_embd: [768]
  # router_type: ['switch', 'diff']

  # Optimization parameters
  batch_size: [512]  # 8*64
  device_batch_size: [8]  # was 16
  sequence_length: [1024]
  # num_iterations: [6000] # was 4578 before
  num_iterations: [4286]  # 6000 - 1714
  warmup_iters: [0]
  # warmdown_iters: [1714] # was 1308 before
  weight_decay: [0.0]
  use_adamw_opt3: [false]
  # Learning rate parameters
  lr_embed: [0.3]
  lr_head: [0.002]
  # lr_muon: [0.02]
  momentum: [0.95]

  # Evaluation and logging parameters
  val_loss_every: [125]
  val_tokens: [10485760]
  save_every: [200]
  save_only_latest: [true]
  wandb_project: ["modded-nanogpt-moe"]
  output: ["logs"]

  # Run config
  device_0: [true]
  seed: [1000]

  global_load_balance: [true]
  aux_coeff_train: [0.1]
  aux_coeff_val: [0.1]
  aux_use_routed_prob: [true]

  router_type: ['diff_no_softmax']
  warmdown_iters: [0]
  lr_muon: [0.01, 0.015, 0.034, 0.048]

  # lr_theta: [0.001, 0.01, 5.0]
  # theta_load_balance_coeff: [0.1]
  # theta_lb_detach_theta: [false]

  LIST_EXPERT_SIZES:
    - num_experts: [64]
      top_k: [16]
      hidden_dim_scale_factor: [0.5]
    # - num_experts: [64]
    #   top_k: [2]
    #   hidden_dim_scale_factor: [0.5]

    # - num_experts: [128]
    #   top_k: [32]
    #   hidden_dim_scale_factor: [0.25]
    # - num_experts: [128]
    #   top_k: [4]
    #   hidden_dim_scale_factor: [0.25]
    # If 48 exps is too many, comment out the last 2 (lines 64-69)
